### PR TITLE
Minor Revisions for 2020 

### PR DESCRIPTION
**Pull request by lisancao**
- changed slack links to callysto.slack.ca
- redirect geogebra notebook links
- redirect some code source links in nbplus 
- fixed spelling errors
- fixed broken links 
- replaced git-nb-tools section with a Jupyter and git diff guide 
- replaced google form for issues with a guide on submitting github issues

### CODE REVIEW

**Comment by lisancao** [comment]
related Jira: CC-858

**Comment by misterhay** [comment]
Slack links should be to callysto.slack.com

**Comment by lisancao** [comment]
Done.

**Review by misterhay — APPROVED** [review]
Looks great

**Pull request merged**
