### PR TITLE
Add shorts repo link, filename convention, attribution

### PR DESCRIPTION
**Pull request by lisancao**
- add shorts link to internal-links, infovis, and useful-links
- add naming convention line to notebook-format
- add attribution to Lisa Cao in README

 On branch update

### CODE REVIEW

**Review by byrcyb — COMMENTED** [review]
We should just change the README to "By the Callysto development team." If folks are really curious about the folks behind the scenes they can have a look at the contributors. Other than that the changes look ok to me.

**Comment by lisancao** [comment]
> We should just change the README to "By the Callysto development team." If folks are really curious about the folks behind the scenes they can have a look at the contributors. Other than that the changes look ok to me.

Done!

**Review by byrcyb — CHANGES_REQUESTED** [review]
As per the comment, I would modify the readme so that it says "By the Callysto development team."

**Comment by lisancao** [comment]
> As per the comment, I would modify the readme so that it says "By the Callysto development team."

Yep, see https://github.com/callysto/training-manual-live/pull/10/commits/22653caf8458d8127f5911068f3198117a271010

**Review by byrcyb — APPROVED** [review]

**Pull request merged**
